language: node_js

node_js:
  - 12
  - 10.13

cache:
  npm: false

branches:
  only:
    - master
    - /^greenkeeper.*$/

install:
  - travis_retry npm install

script:
  - npm run test

after_success:
  - npm run codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
